name: ml-workshop-advanced
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scikit-learn=0.23.*
  - seaborn=0.11.*
  - pandas=1.1.*
  - jupyterlab=2.2.*
  - imbalanced-learn=0.7.*
